version: "3"
services:
  java:
    build:
      context: .
      dockerfile: docker/dockerfile-java
    volumes:
       - ./:/code
       - ${ROOT_CA}:/usr/local/share/ca-certificates/rootCA.pem
    working_dir: /code
    command: ["./mvnw spring-boot:run"]
    ports:
      - "8085:8085"
    extra_hosts:
      - "${AUTH_DOMAIN_NAME}:${DOCKER_HOST_IP}"
